---
driver:
  name: vagrant
  driver:
    customize:
      memory: 4096
      #cpuexecutioncap: 50
#--------------------------------------------------
#   network:
#     - ["forwarded_port", {guest: 80, host: 8080}]
#     - ["private_network", {ip: "192.168.33.33"}]
#-------------------------------------------------- 
  synced_folders: 
    - [".", "/opt/mesos-rpm"]
    #- ["data/%{instance_name}", "/opt/instance_data"],
    #- ["/host_path", "/vm_path", "create: true, type: :nfs"]

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.5

suites:
  - name: default
    run_list:
      - recipe[yum::default]
      - recipe[java::default]
      - recipe[mesos-buildbox::packages]
    attributes:
      java:
        jdk_version: "8"
        java_home: "/usr/lib/jvm/default-java"
        install_flavor: "oracle"
        oracle:
          accept_oracle_download_terms: true
